[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
]

[fmt]
single_line_statement_blocks = "preserve"
params_first = true

[lint]
ignore = [
  "**/*.t.sol",
]
exclude_lints = [
  "asm-keccak256",
  "mixed-case-variable",
  "mixed-case-function",
  "screaming-snake-case-immutable",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
